import type {
  Facility,
  LoyaltyReward,
  MembershipPlan,
  OrderExtra,
  Promo,
  TimeSlot,
} from "./models";

export const facilities: Facility[] = [
  {
    id: "fac-1",
    name: "Sede Central Norte - Planta 1",
    address: "Av. Las Palmeras 104, Miraflores",
    openingHours: "Lun - Sáb: 08:00 - 20:00",
    phone: "+51 987 654 000",
    acceptsDropoff: true,
    allowsPickup: true,
    latitude: -12.084,
    longitude: -77.03,
  },
  {
    id: "fac-2",
    name: "Sede Sur - Chacarilla",
    address: "Av. Primavera 650, Santiago de Surco",
    openingHours: "Lun - Sáb: 08:30 - 19:30",
    phone: "+51 987 654 002",
    acceptsDropoff: true,
    allowsPickup: true,
    latitude: -12.109,
    longitude: -76.992,
  },
  {
    id: "fac-3",
    name: "Sede San Isidro - Centro Financiero",
    address: "Calle Begonias 412, San Isidro",
    openingHours: "Lun - Vie: 08:00 - 19:00",
    phone: "+51 987 654 003",
    acceptsDropoff: true,
    allowsPickup: true,
    latitude: -12.094,
    longitude: -77.026,
  },
];
export const garments = [
  {
    id: "g-1",
    name: "Camisas / Blusas",
    category: "Prendas superiores",
    basePrice: 2.5,
    estimatedHours: 24,
    iconKey: "shirt-outline",
  },
  {
    id: "g-2",
    name: "Pantalones / Jeans",
    category: "Prendas inferiores",
    basePrice: 3,
    estimatedHours: 24,
    iconKey: "shirt-outline",
  },
  {
    id: "g-3",
    name: "Vestidos",
    category: "Prendas delicadas",
    basePrice: 5.5,
    estimatedHours: 48,
    iconKey: "shirt-outline",
  },
  {
    id: "g-4",
    name: "Ropa interior (pack x3)",
    category: "Ropa íntima",
    basePrice: 2,
    estimatedHours: 24,
    iconKey: "shirt-outline",
  },
  {
    id: "g-5",
    name: "Calcetines (pack x3)",
    category: "Ropa íntima",
    basePrice: 1.8,
    estimatedHours: 24,
    iconKey: "shirt-outline",
  },
  {
    id: "g-6",
    name: "Juego de Sábanas",
    category: "Hogar",
    basePrice: 4.5,
    estimatedHours: 24,
    iconKey: "bed-outline",
  },
  {
    id: "g-7",
    name: "Edredón / Plumón",
    category: "Hogar",
    basePrice: 8,
    estimatedHours: 48,
    iconKey: "bed-outline",
  },
  {
    id: "g-8",
    name: "Toallas (juego x2)",
    category: "Hogar",
    basePrice: 3.2,
    estimatedHours: 24,
    iconKey: "layers-outline",
  },
  {
    id: "g-9",
    name: "Chaquetas / Abrigos",
    category: "Prendas exteriores",
    basePrice: 6,
    estimatedHours: 48,
    iconKey: "shirt-outline",
  },
  {
    id: "g-10",
    name: "Traje sastre (2 piezas)",
    category: "Formal",
    basePrice: 9,
    estimatedHours: 48,
    iconKey: "shirt-outline",
  },
];
export const services = [
  {
    id: "s-1",
    name: "Lavado ecológico",
    description: "Lavado suave con agua ozonizada y detergente bio",
    extraPrice: 0,
  },
  {
    id: "s-2",
    name: "Lavado + Secado",
    description: "Lavado completo y secado a temperatura controlada",
    extraPrice: 0.5,
  },
  {
    id: "s-3",
    name: "Lavado + Planchado",
    description: "Servicio integral con vapor anti-arrugas",
    extraPrice: 1.5,
  },
  {
    id: "s-4",
    name: "Solo Planchado",
    description: "Prensado profesional y colgado en funda",
    extraPrice: 1,
  },
  {
    id: "s-5",
    name: "Tratamiento especial",
    description: "Desmanchado focalizado y protección de fibras",
    extraPrice: 2.5,
  },
];
export const extras: OrderExtra[] = [
  {
    id: "ext-1",
    name: "Doblado especial tipo hotel",
    description: "Prendas compactas y listas para closet",
    price: 1.5,
  },
  {
    id: "ext-2",
    name: "Perfumado Clean & Fresh",
    description: "Esencia botánica fresca hipoalergénica",
    price: 1,
  },
  {
    id: "ext-3",
    name: "Empaque premium biodegradable",
    description: "Bolsas de algodón y fundas reutilizables",
    price: 2,
  },
  {
    id: "ext-4",
    name: "Hipoalergénico piel sensible",
    description: "Cero fragancias sintéticas, neutralización total",
    price: 1.5,
  },
];
export const promos: Promo[] = [
  {
    code: "FRESH10",
    discountPercent: 10,
    fixedDiscount: 0,
    minOrderAmount: 15,
    description: "10% de descuento en tu servicio",
    validUntil: "2026-10-31",
  },
  {
    code: "BIENVENIDO",
    discountPercent: 0,
    fixedDiscount: 5,
    minOrderAmount: 20,
    description: "$5.00 de descuento en pedidos mayores a $20",
    validUntil: "2026-11-15",
  },
  {
    code: "LAVADOFACIL",
    discountPercent: 15,
    fixedDiscount: 0,
    minOrderAmount: 25,
    description: "15% para clientes frecuentes",
    validUntil: "2026-11-30",
  },
];
export const rewards: LoyaltyReward[] = [
  {
    id: "rew-1",
    title: "Lavado gratis de edredón",
    pointsCost: 600,
    description: "Canjeable en cualquier solicitud que incluya edredón",
    category: "Hogar",
  },
  {
    id: "rew-2",
    title: "Cupón de $10.00 de saldo",
    pointsCost: 500,
    description: "Se acredita a tu Billetera Laundry después de aprobación",
    category: "Saldo",
  },
  {
    id: "rew-3",
    title: "Perfumado Clean & Fresh gratis",
    pointsCost: 150,
    description: "Extra de aromatizado botánico sin costo",
    category: "Extras",
  },
  {
    id: "rew-4",
    title: "Empaque premium gratis",
    pointsCost: 250,
    description: "Protección ecológica para tu siguiente entrega",
    category: "Extras",
  },
];
export const plans: MembershipPlan[] = [
  {
    id: "plan-basic",
    name: "Básico",
    priceMonthly: 9.99,
    weeklyPickups: 1,
    garmentDiscountPercent: 5,
    benefits: [
      "1 recogida semanal sin costo de envío",
      "5% de descuento en catálogo",
      "Soporte estándar",
    ],
  },
  {
    id: "plan-standard",
    name: "Estándar",
    priceMonthly: 19.99,
    weeklyPickups: 2,
    garmentDiscountPercent: 12,
    benefits: [
      "2 recogidas semanales prioritarias",
      "12% de descuento en todas las prendas",
      "Perfumado fresco de cortesía",
      "Soporte preferente",
    ],
  },
  {
    id: "plan-premium",
    name: "Premium",
    priceMonthly: 34.99,
    weeklyPickups: 4,
    garmentDiscountPercent: 20,
    benefits: [
      "Recogidas ilimitadas bajo demanda",
      "20% de descuento en catálogo y extras",
      "Tratamiento desmanchador incluido",
      "Atención VIP 24/7",
      "Doblado de lujo sin costo",
    ],
  },
];
export const initialSlots: TimeSlot[] = [
  {
    id: "slot-1",
    context: "DRIVER_PICKUP",
    date: "HOY",
    startTime: "09:00",
    endTime: "11:00",
    capacity: 4,
    reservedCount: 4,
    active: true,
  },
  {
    id: "slot-2",
    context: "DRIVER_PICKUP",
    date: "HOY",
    startTime: "11:00",
    endTime: "13:00",
    capacity: 4,
    reservedCount: 3,
    active: true,
  },
  {
    id: "slot-3",
    context: "DRIVER_PICKUP",
    date: "HOY",
    startTime: "16:00",
    endTime: "18:00",
    capacity: 4,
    reservedCount: 1,
    active: true,
  },
  {
    id: "slot-4",
    context: "DRIVER_PICKUP",
    date: "HOY",
    startTime: "18:00",
    endTime: "20:00",
    capacity: 4,
    reservedCount: 0,
    active: true,
  },
  {
    id: "slot-5",
    context: "FACILITY_DROPOFF",
    date: "HOY",
    startTime: "10:00",
    endTime: "12:00",
    capacity: 6,
    reservedCount: 2,
    active: true,
  },
  {
    id: "slot-6",
    context: "FACILITY_DROPOFF",
    date: "HOY",
    startTime: "16:00",
    endTime: "18:00",
    capacity: 6,
    reservedCount: 1,
    active: true,
  },
  {
    id: "slot-7",
    context: "DRIVER_DELIVERY",
    date: "Mañana",
    startTime: "10:00",
    endTime: "12:00",
    capacity: 4,
    reservedCount: 1,
    active: true,
  },
  {
    id: "slot-8",
    context: "DRIVER_DELIVERY",
    date: "Mañana",
    startTime: "16:00",
    endTime: "18:00",
    capacity: 4,
    reservedCount: 2,
    active: true,
  },
  {
    id: "slot-9",
    context: "FACILITY_PICKUP",
    date: "Mañana",
    startTime: "09:00",
    endTime: "12:00",
    capacity: 8,
    reservedCount: 2,
    active: true,
  },
  {
    id: "slot-10",
    context: "FACILITY_PICKUP",
    date: "Mañana",
    startTime: "16:00",
    endTime: "19:00",
    capacity: 8,
    reservedCount: 1,
    active: true,
  },
];
